openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker App
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: This is a documentation of Water tracker App
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Users operations.
  - name: Water
    description: Operations to track the water the user drinks.
  - name: Water{id}
    description: Operations with glass.
servers:
  - url: http://localhost:3000
  - url: https://aqua-tracker-be.onrender.com
paths:
  /auth/signup:
    post:
      $ref: ../swagger/paths/auth/signup.yaml
  /auth/signin:
    post:
      $ref: ../swagger/paths/auth/signin.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/users/current.yaml
  /users/update:
    patch:
      $ref: ../swagger/paths/users/update.yaml
  /users/avatar:
    patch:
      $ref: ../swagger/paths/users/avatar.yaml
  /users/waterRate:
    patch:
      $ref: ../swagger/paths/users/waterRate.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/addWater.yaml
    get:
      $ref: ../swagger/paths/water/getWater.yaml
  /water/{year}/{month}:
    get:
      $ref: ../swagger/paths/water/getMonthly.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/updateAmount.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
